### ISSUE TITLE
Gracefully handle player record when its None

### ISSUE THREAD

**Issue by brbeaird** [derek-adair/nflgame#33] opened 2018-09-11 13:52 UTC
Update players does not gracefully handle missing player records;
```
Could not get GSIS id at http://www.nfl.com/player/cedwilson/2560936/profile

Could not find gsis_id for {'status': u'RES', 'last_name': u'Wilson', 'weight': 197, 'profile_id': 2560936, 'number': 16, 'height': 74, 'college': u'Bowie State', 'full_name': u'Ced Wilson', 'first_name': u'Ced', 'years_pro': 0, 'birthdate': u'3/10/1995', 'team': 'DAL', 'position': u'WR', 'profile_url': 'http://www.nfl.com/player/cedwilson/2560936/profile'}
```

**Comment by 19eddiedean19** [comment] 2018-09-11 20:20
yes, this is normal. You would normally get this is a player does not yet have any recorded stats

**Comment by derek-adair** [comment] 2018-09-13 19:16
Definitely not the first but i'll be cataloging this as an enhancement to gracefully handle this.

**Comment by mickeelm** [comment] 2018-09-15 12:39
How is this not graceful? E.g. what would you prefer instead?

**Comment by derek-adair** [comment] 2018-09-17 17:49
I am under the impression that the script locks up? ya?

If it isn't locking up we can probably close this.  Maybe clarify the message that this is an expected failure somehow.  Simply prepending INFO: or WARNING: is a decent improvement, but definitely not a bug.

**Comment by derek-adair** [comment] 2018-09-17 18:06
I think the main thing is actually the way the messages are reported.  The blob at the end of update_players.py is what lead me to believe the script had exited and failed, it is unclear with this message if the data was updated or not.

Therefore; Gracefully handling these errors amounts to removing the big generic and misleading "error message" and clarifying what is actually an error vs. an NFL data issue.

**Comment by derek-adair** [comment] 2018-09-17 18:07
For this specific issue i think the best thing is to just print out the messages and not append them to the errors dict which is read at the end of the script.

**Comment by mickeelm** [comment] 2018-09-17 20:13
Right, I guess one could think of these messages as network problems or other kinds of errors, maybe it could be clearer that the data we were looking for on nfl.com didn't exist. Not sure how to phrase it but that could be made clearer.

> For this specific issue i think the best thing is to just print out the messages and not append them to the errors dict which is read at the end of the script.

I agree, we'll get a more flow-like feeling if the errors/whatever we call it are printed as they happen. A summary at the end is nice (not with all messages again but a count of errors or so) but it feels more clear and script-ish to print right away. Good suggestion.

**Comment by derek-adair** [comment] 2018-09-18 15:57
I'll take this one.

**Comment by derek-adair** [comment] 2018-10-22 17:18
Need to re-evaluate this once we swap streams related to (#46)

**Comment by derek-adair** [comment] 2020-05-02 00:40
Looking closer this is fine.  I'm not sure what else we can do here.

**Closed by derek-adair** 2020-05-02 00:40 UTC
Labels: enhancement, on hold
