### ISSUE TITLE
Update Player/Schedule Error popping up on both python 2.7/3.7 versions

### ISSUE THREAD

**Issue by Coop197823** [derek-adair/nflgame#90] opened 2019-11-06 00:52 UTC
I have been running both 2.7 and 3.7 versions flawlessly so far from the start of this year.  However when I went to run it tonight, I am getting an error: 

httplib2.RedirectLimit: Redirected more times than redirection_limit allows

on both the 2.7 and 3.7 versions.  I am running both the most up-to-date versions.  It runs through the cycle till about 50% of the update then hits this error and crashes.
Here is the full error:

3.7
![image](https://user-images.githubusercontent.com/5271425/68258770-c64d1b80-0005-11ea-9df7-6da209f0364b.png)

2.7
![image](https://user-images.githubusercontent.com/5271425/68258839-02807c00-0006-11ea-8591-fc1a9f9bee95.png)

**Comment by Coop197823** [comment] 2019-11-06 02:56
Here is the full error when I run in the 3.7 shell:

Loading games for REG 2019 week 9
Finding (profile id -> gsis id) mapping for players...

1/4 complete. (25.00%)
2/4 complete. (50.00%)
3/4 complete. (75.00%)
4/4 complete. (100.00%)
Done!
Downloading team rosters...

1/33 complete. (3.03%)
2/33 complete. (6.06%)
3/33 complete. (9.09%)
4/33 complete. (12.12%)
5/33 complete. (15.15%)
6/33 complete. (18.18%)
7/33 complete. (21.21%)
8/33 complete. (24.24%)
9/33 complete. (27.27%)
10/33 complete. (30.30%)
11/33 complete. (33.33%)
12/33 complete. (36.36%)
13/33 complete. (39.39%)
14/33 complete. (42.42%)Traceback (most recent call last):
  File "C:\Python37\Scripts\nflgame-update-players.py", line 4, in <module>
    nflgame.update_players.run()
  File "C:\Python37\lib\site-packages\nflgame\update_players.py", line 400, in run
    for i, (team, soup) in enumerate(pool.imap(fetch, teams), 1):
  File "C:\Python37\lib\multiprocessing\pool.py", line 748, in next
    raise value
  File "C:\Python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Python37\lib\site-packages\nflgame\update_players.py", line 399, in fetch
    return team, roster_soup(team)
  File "C:\Python37\lib\site-packages\nflgame\update_players.py", line 122, in roster_soup
    resp = requests.get(urls['roster'], params={'team':team})
  File "C:\Python37\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python37\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python37\lib\site-packages\requests\sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Python37\lib\site-packages\requests\sessions.py", line 668, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Python37\lib\site-packages\requests\sessions.py", line 165, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

**Comment by Coop197823** [comment] 2019-11-06 12:48
I have done a complete uninstall, reinstall of both Python 2.7 and 3.7 to 3.8, as well as the latest versions of nflgame 1.2.3 and nflgame-redux==2.0.1b1.  The same error still appears.

For some reason the error is with the multiprocessing\pool.py package.  

I have also tried older versions of the nflgame and the same error occurs.

**Comment by Coop197823** [comment] 2019-11-06 14:55
I have tried it now on a second computer, and get the same error

**Comment by Coop197823** [comment] 2019-11-06 19:10
I fixed it by adding  - 

, allow_redirects=False 

to line 122 in 

update_players.py  

so the whole line should be: 

    resp = requests.get(urls['roster'], params={'team':team}, allow_redirects=False)

You may want to add this to your code

**Comment by Coop197823** [comment] 2019-11-06 19:33
That solved the error for nflgame-redux==2.0.1b1, but not for nflgame 1.2.3 as I am not sure how to fix that one

**Comment by Coop197823** [comment] 2019-11-06 19:59
There still seems to be some serious issues with the data coming from nfl.com.  Even with the fix, I am only getting 20 of the 30 teams that played past week, and only half of those rosters stats.  At this point, I am not sure if it is the code of something on nfl.com's end.

**Comment by ronwill06** [comment] 2019-11-06 21:37
@Coop197823 It looks like their API for this endpoint has a redirect limit. Do you know if their API is public?
I can explore this for you.

**Comment by ronwill06** [comment] 2019-11-06 21:38
Just found the API. Digging in now.

**Comment by ronwill06** [comment] 2019-11-06 22:14
Both screenshots also look like they're from Python 2.7. This version is no longer supported by this library.

**Comment by Coop197823** [comment] 2019-11-06 22:21
@ronwill06 sorry, yep you are right.  I did post the full module run from 3.7in comment 2

**Comment by Coop197823** [comment] 2019-11-06 22:24
Here is 3.7:

![image](https://user-images.githubusercontent.com/5271425/68343205-3e751900-00ba-11ea-8e8f-816964157d64.png)

**Comment by ronwill06** [comment] 2019-11-06 22:37
Thank You

**Comment by ronwill06** [comment] 2019-11-06 22:55
Can you try changing to the `rosters` endpoint to this?  `'roster': 'http://www.nfl.com/v1/teams/roster',`

**Comment by ronwill06** [comment] 2019-11-06 22:59
From just a rough pass, it looks like some of the endpoints may have changed. Here's the link to all of the endpoints if you want to see what I'm talking about. https://api.nfl.com/docs/global/endpoints/index.html

**Comment by Coop197823** [comment] 2019-11-06 23:04
So that ran all the way through, but no rosters were found.  I also did not see the 'roster' endpoint there:

Loading games for REG 2019 week 10
Downloading team rosters...

1/33 complete. (3.03%)
2/33 complete. (6.06%)
3/33 complete. (9.09%)
4/33 complete. (12.12%)
5/33 complete. (15.15%)
6/33 complete. (18.18%)
7/33 complete. (21.21%)
8/33 complete. (24.24%)
9/33 complete. (27.27%)
10/33 complete. (30.30%)
11/33 complete. (33.33%)
12/33 complete. (36.36%)
13/33 complete. (39.39%)
14/33 complete. (42.42%)
15/33 complete. (45.45%)
16/33 complete. (48.48%)
17/33 complete. (51.52%)
18/33 complete. (54.55%)
19/33 complete. (57.58%)
20/33 complete. (60.61%)
21/33 complete. (63.64%)
22/33 complete. (66.67%)
23/33 complete. (69.70%)
24/33 complete. (72.73%)
25/33 complete. (75.76%)
26/33 complete. (78.79%)
27/33 complete. (81.82%)
28/33 complete. (84.85%)
29/33 complete. (87.88%)
30/33 complete. (90.91%)
31/33 complete. (93.94%)
32/33 complete. (96.97%)
33/33 complete. (100.00%)
Done!


There were some errors during the download. Usually this is a
result of an HTTP request timing out, which means the
resulting "players.json" file is probably missing some data.
An appropriate solution is to re-run the script until there
are no more errors (or when the errors are problems on 
NFL.com side.)
-------------------------------------------------------------------------------
Could not get roster for team ARI
-------------------------------------------------------------------------------
Could not get roster for team ATL
-------------------------------------------------------------------------------
Could not get roster for team BAL
-------------------------------------------------------------------------------
Could not get roster for team BUF
-------------------------------------------------------------------------------
Could not get roster for team CAR
-------------------------------------------------------------------------------
Could not get roster for team CHI
-------------------------------------------------------------------------------
Could not get roster for team CIN
-------------------------------------------------------------------------------
Could not get roster for team CLE
-------------------------------------------------------------------------------
Could not get roster for team DAL
-------------------------------------------------------------------------------
Could not get roster for team DEN
-------------------------------------------------------------------------------
Could not get roster for team DET
-------------------------------------------------------------------------------
Could not get roster for team GB
-------------------------------------------------------------------------------
Could not get roster for team HOU
-------------------------------------------------------------------------------
Could not get roster for team IND
-------------------------------------------------------------------------------
Could not get roster for team JAC
-------------------------------------------------------------------------------
Could not get roster for team KC
-------------------------------------------------------------------------------
Could not get roster for team LA
-------------------------------------------------------------------------------
Could not get roster for team SD
-------------------------------------------------------------------------------
Could not get roster for team LAC
-------------------------------------------------------------------------------
Could not get roster for team MIA
-------------------------------------------------------------------------------
Could not get roster for team MIN
-------------------------------------------------------------------------------
Could not get roster for team NE
-------------------------------------------------------------------------------
Could not get roster for team NO
-------------------------------------------------------------------------------
Could not get roster for team NYG
-------------------------------------------------------------------------------
Could not get roster for team NYJ
-------------------------------------------------------------------------------
Could not get roster for team OAK
-------------------------------------------------------------------------------
Could not get roster for team PHI
-------------------------------------------------------------------------------
Could not get roster for team PIT
-------------------------------------------------------------------------------
Could not get roster for team SEA
-------------------------------------------------------------------------------
Could not get roster for team SF
-------------------------------------------------------------------------------
Could not get roster for team TB
-------------------------------------------------------------------------------
Could not get roster for team TEN
-------------------------------------------------------------------------------
Could not get roster for team WAS

**Comment by Coop197823** [comment] 2019-11-06 23:13
I played around with updated the urls by adding the /v1/ into them, and to no avail.  still getting the same errors with no rosters populating

**Comment by blcooley** [comment] 2019-11-07 00:08
It looks like what is happening is that the URL is redirecting on the `team` parameter when the value is `JAC` (to `JAX`) or `SD` (to `LAC`). One possibility would be to replace the `requests.get` call with `requests.head` but I'm not confident in putting up a PR because I'm not sure what result I'm looking for. Unfortunately, I haven't used this library before. @Coop197823 what is a correct result from running the script?

When I ran it, I got the following errors, which seem minor and maybe even expected, but I'm not sure.

`Could not get GSIS id at http://www.nfl.com/player/lofalemaka/2563343/profile
-------------------------------------------------------------------------------
Could not get GSIS id at http://www.nfl.com/player/nateharvey/2563061/profile
-------------------------------------------------------------------------------
Could not find gsis_id for {'team': 'CLE', 'profile_id': 2563343, 'profile_url': 'http://www.nfl.com/player/lofalemaka/2563343/profile', 'number': 0, 'first_name': 'Lo', 'last_name': 'Falemaka', 'full_name': 'Lo Falemaka', 'position': 'C', 'status': 'RES', 'height': 77, 'weight': 295, 'birthdate': '//', 'years_pro': 0, 'college': 'Utah'}
-------------------------------------------------------------------------------
Could not find gsis_id for {'team': 'NYG', 'profile_id': 2563061, 'profile_url': 'http://www.nfl.com/player/nateharvey/2563061/profile', 'number': 0, 'first_name': 'Nate', 'last_name': 'Harvey', 'full_name': 'Nate Harvey', 'position': 'DE', 'status': 'RES', 'height': 73, 'weight': 225, 'birthdate': '9/15/1996', 'years_pro': 0, 'college': 'East Carolina'}
`

**Comment by Coop197823** [comment] 2019-11-07 00:15
sure, what happens when we run it this way, is we lose half the rostered players (goes from usually about 30 to 35 who record some stats down to 15 to 16), and the total teams it pulls data on goes from 30 (on a given week) to 20 or so.  essentially almost half the data is missing.  

As you thought, I tried replacing request.get with request.head, and the errors still persisted without the proper resolution

**Comment by erickgkivi** [comment] 2019-11-07 00:25
I see https://github.com/derek-adair/nflgame/blob/master/nflgame/update_players.py#L70 uses endpoint 'http://www.nfl.com/players/profile'

Via the API docs I see the player lies under the a person domain now: https://api.nfl.com/docs/league/models/person/index.html

Has this always been the case? Perhaps this is the reason why the players.json file is missing data?

**Comment by Coop197823** [comment] 2019-11-07 00:39
so should the urls now be:

urls = {
    'roster': 'http://www.nfl.com/v1/teams/roster',
    'gsis_profile': 'http://www.nfl.com/v1/persons',
}
?

How would that then change the rest of the code as it looks like these are the three next important modules that pll from the url:

def initial_mappings(conf):
    metas, reverse = {}, {}
    try:
        with open(conf.json_update_file) as fp:
            metas = json.load(fp)
        for gsis_id, meta in list(metas.items()):
            reverse[meta['profile_id']] = gsis_id
    except IOError as e:
        eprint('Could not open "%s": %s' % (conf.json_update_file, e))
    # Delete some keys in every entry. We do this to stay fresh.
    # e.g., any player with "team" set should be actively on a roster.
    for k in metas:
        metas[k].pop('team', None)
        metas[k].pop('status', None)
        metas[k].pop('position', None)
    return metas, reverse


def profile_id_from_url(url):
    if url is None:
        return None
    m = re.search('/([0-9]+)/', url)
    return None if m is None else int(m.group(1))


def profile_url(gsis_id):
    resp = requests.head(urls['gsis_profile'], params={'id':gsis_id})
    if resp.status_code != 301:
        return None
    loc = resp.headers['location']
    if not loc.startswith('http://'):
        loc = 'http://www.nfl.com' + loc
    return loc

**Comment by erickgkivi** [comment] 2019-11-07 01:54
I can't find an API version history to see how the data was previously structured.

From the current docs, it looks like the `gsisId` field is at the persons level (i.e. v1/persons/gsid). However, the fields such as `team`, `position`, and `rosterStatus` are at the player level (i.e. v1/persons/player/team)

Is the code dynamic enough to drill down to the player level data if it is now nested in a deeper layer? 

Hopefully I am not way off base on this thought.

**Comment by brianzhou13** [comment] 2019-11-07 02:09
I might be reading it incorrectly... but it looks like the usage of that `gsis_profile` key doesn't look to follow the examples of how `/persons` is used in the NFL documentation.

**Comment by blcooley** [comment] 2019-11-07 02:16
It seems like if the new NFL Shield API is what is to be used then a lot of changes will have to be made. For example, the docs at https://api.nfl.com/docs/global/playbook/index.html say that "Most Shield API requests will require the use of access tokens which your app can generate by using Shield's Identity system."

However, I don't see any requests to the endpoint to get a token.

The biggest thing I see is that the JAC roster import has a bad redirect on the NFL side (it is appending &team=JAX to the original URL and creating a redirect loop.) From what I can tell, the easiest way to fix this is to go into `__init.py` and change line 29 from
    
`['JAC', 'Jacksonville', 'Jaguars', 'Jacksonville Jaguars', 'JAX'],
`
to
`['JAX', 'Jacksonville', 'Jaguars', 'Jacksonville Jaguars', 'JAC'],
`
This avoids the redirect loop. It's also not used in many other places, so it shouldn't break anything else.

When I run this, the players.json file ends up with a little over 8600 elements in the top level dictionary, which is slightly more than what is in the repo.

**Comment by brianzhou13** [comment] 2019-11-07 02:26
Yeah, that should work. I have a PR out that does just that: https://github.com/derek-adair/nflgame/pull/91/files#diff-d9c36557288cd83747412b9790e06104R129

**Comment by 903124** [comment] 2019-11-07 02:46
For a safe route it can be changed to `    teams = [team[0] for team in nflgame.teams if (team[0] != 'STL' and team[0] != 'SD') ]
    
    teams = [team.replace('JAC', 'JAX') for team in teams]`

**Comment by mickeelm** [comment] 2019-11-07 06:26
Since the NFL Shield API documentation is up, I'm just reminding of #46. TL;DR: All (and I'm pretty sure that's ALL) the info that you can get from NFL.com, you can get in JSON/XML, no tokens or nothing, just plain requests without auth like today. 

This means that there's a lot of rewriting that _can_ be done if one has the energy (and this application can be extended to a lot more).This application uses older feeds mainly, and the player info is retrieved "hacky" (not complaining, as I've written probably five times before, that was the best that could've been done at the time).

Please see the discussions/examples in that thread. Let me know if you have any questions, I'll try to answer.

**Comment by Coop197823** [comment] 2019-11-07 15:27
Looks like with the fixes, two team's data is still missing CLE and DEN who played each other in week 9

**Comment by ronwill06** [comment] 2019-11-07 18:27
It looks like those two teams may have the same issue that @blcooley called out.

**Comment by Coop197823** [comment] 2019-11-07 18:33
@ronwill06 Did their names change in the nfl.com api?

**Comment by johnbartkiw** [comment] 2019-11-07 18:53
Not sure if it's related to the problem with player data but when I do a call to nflgame.games(2019, week=9) I only get back 11 records instead of the expected 14.  The games that aren't returned are:

CLE/DEN
GB/LAC
DAL/NYG

**Comment by Coop197823** [comment] 2019-11-07 20:10
when I run:
```

games = nflgame.games(2019, week=9)
nflgame.nflgame.combine_max_stats(games)
```
I get 26 teams with just CLE/DEN missing, that is after I have made all the changes based on the PR changes

**Comment by dijatool** [comment] 2019-11-08 05:03
I don't know what to branch where to get a working version for python 2.7 or I'd do a quick patch file so here are at least 2 known issues on nfl.com that are causing your issues.

The default page handler at nfl.com now returns gzip encoded pages by default. nflgame uses urllib2 so it has all the data needed to handle things properly but it doesn't. This also broke the R folks. It's an old problem.

For all the places where pages get loaded you need a thin wrapper that does something like this...


def nflcom_http_wrapper( url, timeout = 0 )
    resp = urllib2.urlopen( url, timeout = timeout )
    encoding = resp.info().get( 'Content-Encoding', None )
    if encoding == 'gzip' :
        import zlib
        page = zlib.decompress( response.read(), 16 + zlib.MAX_WBITS )
    else :
        page = response.read()
    return page

Add that shim in all the places where pages get loaded and you'll be set.

nflgame/game.py
nflgame/live.py
nflgame/update_sched.py

I also saw a patch file floating around for a change from JAC to JAX. That's the only other problem I've tripped over.

**Comment by dijatool** [comment] 2019-11-08 05:04
I don't know what to branch where to get a working version for python 2.7 or I'd do a quick patch file so here are at least 2 known issues on nfl.com that are causing your issues.

The default page handler at nfl.com now returns gzip encoded pages by default. nflgame uses urllib2 so it has all the data needed to handle things properly but it doesn't. This also broke the R folks. It's an old problem.

For all the places where pages get loaded you need a thin wrapper that does something like this...


def nflcom_http_wrapper( url, timeout = 0 ) :
    '''
    check encoding
    '''
    resp = urllib2.urlopen( url, timeout = timeout )
    encoding = resp.info().get( 'Content-Encoding', None )
    if encoding == 'gzip' :
        import zlib
        page = zlib.decompress( response.read(), 16 + zlib.MAX_WBITS )
    else :
        page = response.read()
    return page


Add that shim in all the places where pages get loaded and you'll be set.

nflgame/game.py
nflgame/live.py
nflgame/update_sched.py


I also saw a patch file floating around for a change from JAC to JAX. That's the only other problem I've tripped over.

**Comment by johnbartkiw** [comment] 2019-11-08 05:30
> I don't know what to branch where to get a working version for python 2.7 or I'd do a quick patch file so here are at least 2 known issues on nfl.com that are causing your issues.
> 
> The default page handler at nfl.com now returns gzip encoded pages by default. nflgame uses urllib2 so it has all the data needed to handle things properly but it doesn't. This also broke the R folks. It's an old problem.
> 
> For all the places where pages get loaded you need a thin wrapper that does something like this...
> 
> def nflcom_http_wrapper( url, timeout = 0 ) :
> '''
> check encoding
> '''
> resp = urllib2.urlopen( url, timeout = timeout )
> encoding = resp.info().get( 'Content-Encoding', None )
> if encoding == 'gzip' :
> import zlib
> page = zlib.decompress( response.read(), 16 + zlib.MAX_WBITS )
> else :
> page = response.read()
> return page
> 
> Add that shim in all the places where pages get loaded and you'll be set.
> 
> nflgame/game.py
> nflgame/live.py
> nflgame/update_sched.py
> 
> I also saw a patch file floating around for a change from JAC to JAX. That's the only other problem I've tripped over.

This works like a charm. Allows me to grab all of the games for the week. Thanks for the heads up!

**Comment by Coop197823** [comment] 2019-11-08 12:20
@johnbartkiw and @dijatool could you provide a bit more of an example where I need to work this code in and maybe one specific location of where the code should go and then what the wrapper with the code would look like?  I apologize, as I am still learning python (and really programming for that matter)!

**Comment by ochawkeye** [comment] 2019-11-08 14:38
For the life of me I cannot get any results for last night's game 2019110700.  I was getting results during the game, but after deleting 2019110700.json the game never gets picked back up.

**Comment by brianzhou13** [comment] 2019-11-08 14:40
@johnbartkiw you think you can cut a PR with your solution?

**Comment by ochawkeye** [comment] 2019-11-08 15:07
Alright, here's the location for `game.py`.


```python
def nflcom_http_wrapper(url, timeout=0):
    """check encoding"""
    resp = urllib2.urlopen(url, timeout=timeout)
    encoding = resp.info().get('Content-Encoding', None)
    if encoding == 'gzip' :
        import zlib
        page = zlib.decompress(resp.read(), 16 + zlib.MAX_WBITS)
    else:
        page = resp.read()
    print page
    return page
...
...
...
def _get_json_data(eid=None, fpath=None):
    """
    Returns the JSON data corresponding to the game represented by eid.

    If the JSON data is already on disk, it is read, decompressed and returned.

    Otherwise, the JSON data is downloaded from the NFL web site. If the data
    doesn't exist yet or there was an error, _get_json_data returns None.

    If eid is None, then the JSON data is read from the file at fpath.
    """
    assert eid is not None or fpath is not None

    if fpath is not None:
        return gzip.open(fpath).read()

    fpath = _jsonf % eid
    if os.access(fpath, os.R_OK):
        return gzip.open(fpath).read()
    try:
        # return urllib2.urlopen(_json_base_url % (eid, eid), timeout=5).read()
        return nflcom_http_wrapper(_json_base_url % (eid, eid), timeout=5)
    except urllib2.HTTPError:
        pass
    except socket.timeout:
        pass
    return None
```

Note that `def nflcom_http_wrapper(url, timeout=0):` differs ever so slightly from what is listed above since the original mixed `resp` and `response` names for same variable.

**Comment by Coop197823** [comment] 2019-11-08 15:12
Does it matter where I place the `def nflcom_http_wrapper(url, timeout=0):` code above the other` def _get_json_data(eid=None, fpath=None):` code?

**Comment by Coop197823** [comment] 2019-11-08 15:59
@ochawkeye or even better, a Pull Request would be much appreciated.

**Comment by johnbartkiw** [comment] 2019-11-08 16:31
@Coop197823 I just put up a PR for game.py that I'm using.

**Comment by ochawkeye** [comment] 2019-11-08 16:47
I never moved off of Python 2.7 so my version of `nflgame` has deviated so far from @derek-adair that it's no longer possible for me to contribute code directly.

**Comment by Coop197823** [comment] 2019-11-08 18:07
@ochawkeye & @johnbartkiw ty all for your help!

**Comment by derek-adair** [comment] 2019-11-11 14:00
I've had an impossibly busy couple weeks.  What an epic thread i've come back to.

OK!

1) This project diverts from python 2.7 starting @ 2.0.x.  Currently, if you simply `pip install nflgame-redux` you will get the last python 2.7 changes.  This will require you to do some monkeying around to get things right.   I'd highly suggest switching to python 3 for a number of reasons that I wont go into here, but i'm afraid I dont have the bandwidth or inclination to maintain any python 2 code.  If anyone wants to fork and maintain a parallel project i'd be happy to endorse it.

2) So it looks like the solution is to handle gzip compression from the stream? As well as deal w/ the JAX/JAC issue?

**Comment by HQuality** [comment] 2019-11-13 23:12
Thanks and please note that you have to use `urllib.request.urlopen` instead of `urllib2.urlopen` in Python 3.x

**Comment by cjmuldoon** [comment] 2020-01-20 06:51
> @ochawkeye & @johnbartkiw ty all for your help!

Given the issue is still open did this solution not work for you?

The only reason I'm running the older version of nflgame is for NFLDB.

I have applied the wrappers as proposed above and still hitting the redirection_limit error.

**Comment by derek-adair** [comment] 2020-04-24 13:02
### PSA - this project does NOT use the official NFL api and never will.

Please see #46

**Comment by derek-adair** [comment] 2020-04-24 13:03
@cjmuldoon Depending on the effort it entails i will be bringing nfldb under my control as well.

**Comment by derek-adair** [comment] 2020-04-24 13:05
ALSO closing this because httplib2 is no longer used in this project.

**Closed by derek-adair** 2020-04-24 13:05 UTC
