### ISSUE TITLE
NFL Current Week Returning Wrong Week

### ISSUE THREAD

**Issue by jbarber3388** [derek-adair/nflgame#106] opened 2020-01-16 04:47 UTC
According to the API and everything I have read, the POST season should be number 1-4. However, the NFL API at http://www.nfl.com/feeds-rs/currentWeek.json is actually returning week 20. I believe this is causing a lot of issues with getting the current playoff data.

![image](https://user-images.githubusercontent.com/30903060/72494123-e44aaf80-37f0-11ea-9512-456fcdf1da9b.png)

A current workaround is using the "POST" phase when updating the schedule and going week by week when updating the players.

(ENV) C:\Users\jpb71\ENV\Lib\site-packages\nflgame>update_sched.py --phase POST
Last updated: 2020-01-16 03:08:36.572015
Updating (2009, POST, 1)...
Updating (2009, POST, 2)...
Updating (2009, POST, 3)...
Updating (2009, POST, 4)...
Updating (2010, POST, 1)...
Updating (2010, POST, 2)...
Updating (2010, POST, 3)...
Updating (2010, POST, 4)...
Updating (2011, POST, 1)...
Updating (2011, POST, 2)...
Updating (2011, POST, 3)...
Updating (2011, POST, 4)...
Updating (2012, POST, 1)...
Updating (2012, POST, 2)...
Updating (2012, POST, 3)...
Updating (2012, POST, 4)...
Updating (2013, POST, 1)...
Updating (2013, POST, 2)...
Updating (2013, POST, 3)...
Updating (2013, POST, 4)...
Updating (2014, POST, 1)...
Updating (2014, POST, 2)...
Updating (2014, POST, 3)...
Updating (2014, POST, 4)...
Updating (2015, POST, 1)...
Updating (2015, POST, 2)...
Updating (2015, POST, 3)...
Updating (2015, POST, 4)...
Updating (2016, POST, 1)...
Updating (2016, POST, 2)...
Updating (2016, POST, 3)...
Updating (2016, POST, 4)...
Updating (2017, POST, 1)...
Updating (2017, POST, 2)...
Updating (2017, POST, 3)...
Updating (2017, POST, 4)...
Updating (2018, POST, 1)...
Updating (2018, POST, 2)...
Updating (2018, POST, 3)...
Updating (2018, POST, 4)...
Updating (2019, POST, 1)...
Updating (2019, POST, 2)...
Updating (2019, POST, 3)...
Updating (2019, POST, 4)...

(ENV) C:\Users\jpb71\ENV\Lib\site-packages\nflgame>update_players.py --phase POST --year 2019 --week 1
Loading games for POST 2019 week 1
Downloading team rosters...
33/33 complete. (100.00%)
Done!
Fetching GSIS identifiers for players not in nflgame...
2/2 complete. (100.00%)
Done!

However, I had to change the get request for the roster to not allow redirects in the update_players.py file. Not sure if it is related at all.

`def roster_soup(team):
    resp = requests.get(urls['roster'], params={'team':team}, allow_redirects=False)
    if resp.status_code != 200:
        return None
    return BeautifulSoup(resp.text, PARSER)`

**Comment by mickeelm** [comment] 2020-01-16 07:12
I haven't been participating in this project for a long time now, but I'm pretty sure nfl.com has always returned 18 for wild card, 19 for divisional, 20 for conference, 21 for pro bowl and 22 for super bowl, at least in feeds that this project has been using. 

This has been internally "translated" before, for instance POST 18 becomes POST 1. 

The problem is most likely this:

*At first*, another endpoint was used (than the one used today), for instance here: https://github.com/derek-adair/nflgame/blob/33991da8a9e513dc1f167575519cb303839da2f2/nflgame/live.py#L355

as you can see, there's some logic to make the week correct (-17).

*Then I wrote* a solution that did not require any external calls at all (and the above solution had to be manually adjusted everytime we went from post- to regual season and vice versa because there were two separate endpoints), because everything can be calculated (the NFL doesn't start at a random time, there are rules and you can apply simple calendar logic). You can check here: https://github.com/derek-adair/nflgame/blob/b65421d8377db1a0175cdfcdcda2b0497fa759f3/nflgame/live.py#L353 

(Wow, I put lots of effort into documenting :D )

Then, Derek found the endpoint currently used and replaced my scheduling logic with the official source of truth (and I thought that was a good idea, just for the record, cause IF the NFL would decide to change their scheduling policy, my logic wouldn't work).

However, it seems he did not take the 17 week offset into account:

https://github.com/derek-adair/nflgame/blob/master/nflgame/live.py#L356

the commit when this was introduced: https://github.com/derek-adair/nflgame/commit/c1970ff667a46ebbdc7370aae506fb199f64f287

**Comment by mickeelm** [comment] 2020-01-16 07:35
So, I just dry coded this is notepad so NO WARRANTY :) But, try to replace lines 361-365 with

```
if (curWeekResponse.ok):
        curWeekJson = curWeekResponse.json()
	week = curWeekJson['week']
	phase = curWeekJson['seasonType']
	if phase == 'PRE' or phase == 'PRO':
		week = -= 17
		
        _cur_week = week
        _cur_season_phase = phase
        _cur_year = curWeekJson['seasonId']
```

**Comment by mickeelm** [comment] 2020-01-17 06:46
@jbarber3388 Did you give it a shot?

**Comment by derek-adair** [comment] 2020-04-23 15:52
I'm currently unsure how to proceed w/ this issue.  Strongly considering updating the convention to match the way feeds-rs defines week_num (as in POST starting at 18 *not* 1).  This would obviously break everyones code.

**Comment by derek-adair** [comment] 2020-04-24 12:47
Closing b/c this is likely a duplicate / side effect of #104.

**Closed by derek-adair** 2020-04-24 12:47 UTC
